version: '3.8'

services:
  app-frontend:
    image: traefik/whoami
    container_name: app-frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-frontend.rule=Host(`app.local`)"
      - "traefik.http.routers.app-frontend.entrypoints=web"
      - "traefik.http.services.app-frontend.loadbalancer.server.port=80"
    networks:
      - app-network
      - shared-network

  app-backend:
    image: traefik/whoami
    container_name: app-backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-backend.rule=Host(`api.app.local`)"
      - "traefik.http.routers.app-backend.entrypoints=web"
      - "traefik.http.services.app-backend.loadbalancer.server.port=80"
    networks:
      - app-network

  app-database:
    image: traefik/whoami
    container_name: app-database
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: app-network
  shared-network:
    external: true
    name: shared-network